# Generated by Django 5.1.6 on 2025-03-03 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('artist', models.CharField(max_length=255, verbose_name='Artista')),
                ('album', models.CharField(max_length=255, verbose_name='Álbum')),
                ('mp3_file', models.FileField(upload_to='music/', verbose_name='Arquivo MP3')),
                ('cover_image', models.ImageField(upload_to='covers/', verbose_name='Imagem de Capa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
            ],
            options={
                'verbose_name': 'Música',
                'verbose_name_plural': 'Músicas',
                'ordering': ['-created_at'],
            },
        ),
    ]
